import { dateTimeString } from '@common/schemas';
import { t } from 'elysia';

/**
 * Firmware module schemas — factory-managed global firmware catalog.
 *
 * All response schemas live here; route files import them (never inline).
 */

/** Rejects ASCII control chars (0x00–0x1F) and DEL (0x7F) — same as artifacts. */
const NO_CONTROL_CHARS = '^[^\\x00-\\x1F\\x7F]*$';

/**
 * Semantic version tag — MAJOR.MINOR.PATCH with optional pre-release/build
 * suffix. This is the "tag da atualização" the factory must provide on every
 * upload (e.g. "4.0.1", "4.1.0-rc.2").
 */
export const SEMVER_PATTERN = '^\\d+\\.\\d+\\.\\d+(?:[-+][0-9A-Za-z.-]+)?$';

/**
 * Factory firmware upload — version tag is REQUIRED (unlike company artifacts).
 *
 * NO `default` here: Elysia APPLIES TypeBox defaults to the parsed body, so a
 * default with example values fabricates data on incomplete requests
 * (production incident: an empty upload arrived as "wifi3 — estabilidade
 * CAN" / "4.0.1"). Examples belong in the route `detail.description` only.
 */
export const UploadFirmwareBodySchema = t.Object({
	file: t.File({
		description:
			'Canonical v4 OTA .tar generated by tools/ota_sign.py + ota_pack.py (repo Ninbus-v4): ' +
			'artifact.info (type "<type>") + data/firmware.npm (128 B signed NPM manifest + image ≤ 192 KiB). ' +
			'firmware-ninbus REQUIRES the .tar (raw .bin is rejected by the device); ' +
			'firmware-controller also accepts a raw .fir (packaged server-side). ' +
			'Max size: ARTIFACT_MAX_SIZE_MB (default 50 MB).',
	}),
	name: t.String({
		minLength: 1,
		maxLength: 256,
		pattern: NO_CONTROL_CHARS,
		description: 'Display name (e.g. "wifi3 — estabilidade CAN")',
	}),
	version: t.String({
		pattern: SEMVER_PATTERN,
		maxLength: 64,
		description: 'Semantic version tag of this release (REQUIRED, e.g. "4.0.1")',
	}),
	artifactType: t.Union(
		[
			t.Literal('firmware-ninbus', { description: 'Ninbus self-update (STM32, reboots)' }),
			t.Literal('firmware-controller', { description: 'Controller/LightDot firmware via CAN' }),
		],
		{ description: 'Firmware type — which component this release updates' },
	),
	description: t.Optional(t.String({ maxLength: 1000, description: 'Optional release notes' })),
	// NOTE: no manual `counter` here — the server derives it AUTOMATICALLY
	// (max(counter)+1 from the catalog, persisted). Zero extra fields in the
	// upload form: file, name, version, type, optional notes.
});

/** A firmware release as stored in the local catalog (DB-only read). */
/** Publication gate evidence — mirrors publication-gate.ts types. */
export const GateCheckSchema = t.Object({
	name: t.String(),
	passed: t.Boolean(),
	detail: t.String(),
});

export const GateResultSchema = t.Object({
	// Read-tolerant: evidence persisted BEFORE a field existed must still
	// serialize (JSONB has no schema migration). Only 'passed' is required.
	passed: t.Boolean(),
	mode: t.Optional(t.Union([t.Literal('publish'), t.Literal('pilot')])),
	checkedAt: t.Optional(t.String()),
	checks: t.Optional(t.Array(GateCheckSchema)),
	imageSha256: t.Optional(t.Union([t.String(), t.Null()])),
	fleetFloorVersion: t.Optional(t.Union([t.String(), t.Null()])),
	catalogMaxCounter: t.Optional(t.Union([t.Number(), t.Null()])),
});

export const FirmwareReleaseSchema = t.Object({
	id: t.String({ format: 'uuid' }),
	name: t.String(),
	version: t.String({ description: 'Semantic version tag (e.g. "4.0.1")' }),
	artifactType: t.String(),
	status: t.Enum(
		{ draft: 'draft', published: 'published' },
		{
			description:
				'Release gate: draft (factory testing, invisible to users) | published (available)',
		},
	),
	description: t.Union([t.String(), t.Null()]),
	originalFilename: t.Union([t.String(), t.Null()]),
	payloadSize: t.Union([t.Number(), t.Null()]),
	packageSize: t.Union([t.Number(), t.Null()]),
	/** Anti-downgrade manifest counter (firmware-ninbus only). Auto: max+1. */
	counter: t.Union([t.Number(), t.Null()]),
	/** NPM manifest v2 packed version u32 — null = v1 legacy/non-ninbus. */
	manifestVersion: t.Union([t.Number(), t.Null()]),
	/** NPM manifest v2 flags (bit0 = allow_downgrade) — null = v1/non-ninbus. */
	manifestFlags: t.Union([t.Number(), t.Null()]),
	/** Publication gate evidence (checks + verdict + image sha256) — null until
	 * the gate runs; REQUIRED to pass before status='published'. */
	gate: t.Union([t.Null(), GateResultSchema]),
	gateAt: t.Union([dateTimeString, t.Null()]),
	createdBy: t.Union([t.String(), t.Null()]),
	createdAt: dateTimeString,
	updatedAt: dateTimeString,
});

export const FirmwareReleaseListResponseSchema = t.Object({
	data: t.Array(FirmwareReleaseSchema),
	total: t.Number(),
});

export const FirmwareLatestResponseSchema = t.Object({
	data: t.Union([FirmwareReleaseSchema, t.Null()], {
		description: 'Latest PUBLISHED release for the requested type, null if none published yet',
	}),
});

export const FirmwarePublishResponseSchema = t.Object({
	message: t.String(),
	data: FirmwareReleaseSchema,
});

export const FirmwareDeleteResponseSchema = t.Object({
	message: t.String(),
	/** true when the binary stays on hawkBit (locked DS = deployment history). */
	hawkbitKept: t.Boolean(),
});

export const FirmwareUploadResponseSchema = t.Object({
	message: t.String(),
	data: t.Optional(
		t.Object({
			releaseId: t.String({ format: 'uuid' }),
			smId: t.Number(),
			artifactId: t.Optional(t.Number()),
			name: t.String(),
			version: t.String(),
			type: t.String(),
			/** Total .tar archive size uploaded to hawkBit. */
			size: t.Number(),
			/** Original raw firmware file size (before tar packaging). */
			payloadSize: t.Optional(t.Number()),
		}),
	),
});

// ── Company-scoped firmware status (mobile) ─────────────────────────

/** Per-device firmware status vs the latest factory release. */
export const DeviceFirmwareStatusSchema = t.Object({
	deviceId: t.String({ format: 'uuid' }),
	name: t.String(),
	serialDisplay: t.Union([t.String(), t.Null()]),
	controllerId: t.Union([t.String(), t.Null()]),
	/** Firmware version the device reported via DDI (null = never reported). */
	firmwareVersion: t.Union([t.String(), t.Null()]),
	/** Controller (peripheral) firmware version reported via DDI. */
	controllerFirmwareVersion: t.Union([t.String(), t.Null()]),
	connectionStatus: t.Union([t.String(), t.Null()]),
	/** hawkBit update status — 'error' means the last OTA attempt failed. */
	hawkbitUpdateStatus: t.Union([t.String(), t.Null()]),
	/**
	 * up_to_date | update_available | unknown | error | no_release
	 *  - update_available → mobile may trigger the update (POST /update)
	 *  - unknown          → device never reported its version via DDI
	 *  - error            → last deployment failed (hawkbitUpdateStatus=error)
	 */
	firmwareStatus: t.String(),
});

export const FirmwareStatusResponseSchema = t.Object({
	/** Latest published releases per firmware type (null = none published). */
	latest: t.Object({
		ninbus: t.Union([FirmwareReleaseSchema, t.Null()]),
		controller: t.Union([FirmwareReleaseSchema, t.Null()]),
	}),
	devices: t.Array(DeviceFirmwareStatusSchema),
	summary: t.Object({
		total: t.Number(),
		upToDate: t.Number(),
		outdated: t.Number(),
		unknown: t.Number(),
		error: t.Number(),
	}),
});

/** POST /devices/firmware/update — trigger the update for selected devices. */
export const TriggerFirmwareUpdateSchema = t.Object({
	deviceIds: t.Array(t.String({ format: 'uuid' }), {
		minItems: 1,
		maxItems: 500,
		description: 'Devices to update (must belong to this company). Cross-tenant ids are dropped.',
	}),
});

// ── Admin-forced deploy (console) ─────────────────────────────────

/** Deployment execution result (shared by mobile trigger and admin force). */
export const FirmwareDeploymentResultSchema = t.Object({
	dsId: t.Number(),
	name: t.String(),
	version: t.String(),
	targetsAssigned: t.Number(),
	artifactType: t.String(),
	smId: t.Number(),
	smName: t.String(),
	verified: t.Number(),
	failed: t.Number(),
	// Operational guard (bench incident: rollout served the OLD published build
	// because the owner's fresh upload was still DRAFT). Present when deploying
	// the latest PUBLISHED release while a NEWER DRAFT exists in the catalog.
	draftWarning: t.Optional(t.String()),
});

/** POST /api/admin/firmware/deploy — admin body (global device selection). */
export const DeployFirmwareBodySchema = t.Object({
	deviceIds: t.Array(t.String({ format: 'uuid' }), {
		minItems: 1,
		maxItems: 500,
		description: 'Devices to update (any company; grouped into per-company deployments).',
	}),
	// Firmware type to deploy — defaults to firmware-ninbus.
	artifactType: t.Optional(
		t.Union([t.Literal('firmware-ninbus'), t.Literal('firmware-controller')]),
	),
	// Explicit release — may be a DRAFT: the admin-console PILOT channel
	// (bench test on assigned devices, guarded by the structural gate).
	// Omitted → latest PUBLISHED release of the type (never a draft).
	releaseId: t.Optional(t.String({ format: 'uuid' })),
	// Escape hatch for REJECTED_ARTIFACT: retry the same release after a
	// transient failure (e.g. devices were offline). The anti-replay floor
	// still applies on the devices themselves.
	force: t.Optional(t.Boolean()),
});

export const FirmwareDeployResponseSchema = t.Object({
	message: t.String(),
	data: t.Object({
		companies: t.Number({ description: 'Deployments created (one per company).' }),
		devices: t.Number({ description: 'Total devices scheduled.' }),
		deployments: t.Array(
			t.Object({
				companyId: t.String({ format: 'uuid' }),
				result: FirmwareDeploymentResultSchema,
			}),
		),
	}),
});

export { ErrorResponseSchema, GenericActionResponseSchema } from '@common/schemas';
