import { createHash } from 'node:crypto';
/**
 * Canonical v4 OTA Tar Validator — server-side port of tools/ota_pack.py
 * (repo Ninbus-v4). Validates the EXACT structure the v4 firmware accepts
 * before the release is stored in hawkBit.
 *
 * GOLDEN RULE (device contract, see docs/firmware-release-flow.md §5):
 * the device NEVER accepts raw .bin/.hex/.elf — only the canonical TAR
 * generated by the Ninbus-v4 tools. Anything else is honestly rejected by
 * the firmware with closed+failure ("REJEITADO: manifesto sem magic NPM" —
 * deployment 657 incident).
 *
 * Canonical structure (USTAR, mtime=0, deterministic — 2 members, in order):
 *
 *   update-app.tar
 *   ├── artifact.info        → 'type "<type>"\n'      (FIRST member, ASCII)
 *   └── data/firmware.npm    → firmware-ninbus: signed manifest (128 B) + image
 *     | data/config.frz      → configuration-nfx: raw payload
 *     | data/controller.fir  → firmware-controller: raw payload
 *
 * The NPM manifest carries the ECDSA P-256 signature over
 * SHA-256(image ‖ LE32(counter) ‖ LE32(size)) — anti-downgrade counter,
 * image size and padding are validated here. The SIGNATURE itself is only
 * verifiable by the bootloader (pubkey burned in flash) — the server cannot
 * and must not hold the private key, so structural validation is the
 * server-side ceiling.
 */
import tar, { type Headers as TarHeaders } from 'tar-stream';

/**
 * Package validation error — mirrors FirmwareValidationError (service.ts)
 * without importing it (service imports this module — no cycles).
 */
export class InvalidPackageError extends Error {
	constructor(
		message: string,
		public readonly code = 'INVALID_PACKAGE',
	) {
		super(message);
		this.name = 'InvalidPackageError';
	}
}

/** Manifest constants — mirror ota_pack.py. */
const MANIFEST_SIZE = 128;
const MANIFEST_MAGIC_V1 = Buffer.from('NPM\x01', 'ascii');
const MANIFEST_MAGIC_V2 = Buffer.from('NPM\x02', 'ascii');
const MAX_IMAGE_SIZE = 0x30000; // 192 KiB

/** Unpack a v2 packed u32 version into its canonical text form. */
export function unpackVersionText(packed: number): string {
	const major = (packed >>> 24) & 0xff;
	const minor = (packed >>> 16) & 0xff;
	const patch = (packed >>> 8) & 0xff;
	const build = packed & 0xff;
	return build === 0 ? `${major}.${minor}.${patch}` : `${major}.${minor}.${patch}.${build}`;
}

/** Canonical data member per artifact type — mirror of CANONICAL_MEMBERS. */
export const CANONICAL_DATA_MEMBERS = {
	'firmware-ninbus': 'data/firmware.npm',
	'configuration-nfx': 'data/config.frz',
	'firmware-controller': 'data/controller.fir',
} as const;

export type CanonicalArtifactType = keyof typeof CANONICAL_DATA_MEMBERS;

/** Parsed facts about a validated canonical tar (for catalog metadata). */
export interface CanonicalTarInfo {
	/** Bytes of the data member (manifest+image for ninbus, payload otherwise). */
	payloadSize: number;
	/** Image bytes only (ninbus); equals payloadSize for the other types. */
	imageSize: number;
	/** Manifest anti-downgrade counter (ninbus only; null otherwise). */
	counter: number | null;
	/** NPM manifest format: 1 (legacy) | 2 (version-piso); null for non-ninbus. */
	manifestFormat: 1 | 2 | null;
	/** Packed version u32 (v2 only; null for v1/non-ninbus). */
	versionPacked: number | null;
	/** Canonical version text (v2 only, e.g. "4.0.4"). */
	versionText: string | null;
	/** v2 bit0: downgrade explicitly allowed by a signed manifest. */
	allowDowngrade: boolean | null;
}

const invalid = (message: string): InvalidPackageError =>
	new InvalidPackageError(message, 'INVALID_PACKAGE');

/**
 * Validate the NPM signed-manifest prefix of a firmware-ninbus payload —
 * direct port of ota_pack.py validate_manifest() (digest included; the
 * ECDSA signature itself is bootloader-only). Accepts BOTH formats:
 *   v1 — magic "NPM\x01", digest over image‖counter‖size, counter @40.
 *   v2 — magic "NPM\x02", version @44 + flags @48 (bit0 only), digest over
 *        image‖counter‖size‖version‖flags (version/flags are signed — a
 *        tampered version or an enabled allow_downgrade breaks the digest).
 */
export function validateNinbusManifest(payload: Buffer, type: string): number {
	if (payload.length < MANIFEST_SIZE) {
		throw invalid(
			`Pacote ${type} inválido: data/firmware.npm tem ${payload.length} B — menor que o manifesto NPM de ${MANIFEST_SIZE} B. Gere o .tar com ota_sign.py + ota_pack.py (repo Ninbus-v4).`,
		);
	}
	const manifest = payload.subarray(0, MANIFEST_SIZE);
	const image = payload.subarray(MANIFEST_SIZE);

	const magic = manifest.subarray(0, 4);
	const isV1 = magic.equals(MANIFEST_MAGIC_V1);
	const isV2 = magic.equals(MANIFEST_MAGIC_V2);
	if (!isV1 && !isV2) {
		throw invalid(
			`Pacote ${type} inválido: manifesto sem magic NPM\\x01/NPM\\x02 (começa com 0x${magic.toString('hex')}). O firmware rejeita na hora — assine a imagem com tools/ota_sign.py antes de subir.`,
		);
	}
	const size = manifest.readUInt32LE(4);
	const counter = manifest.readUInt32LE(40);
	let version: number | null = null;
	let flags = 0;
	let signatureLength: number;
	if (isV2) {
		version = manifest.readUInt32LE(44);
		flags = manifest.readUInt32LE(48);
		signatureLength = manifest[52] ?? 0; // 0 fails the 8–72 range check below
		if (flags & ~0x1) {
			throw invalid(
				`Pacote ${type} inválido: flags do manifesto v2 usam bits reservados (0x${flags.toString(16)}) — apenas bit0 (allow_downgrade) existe.`,
			);
		}
	} else {
		signatureLength = manifest[44] ?? 0; // 0 fails the 8–72 range check below
	}

	if (size !== image.length || size <= 0 || size > MAX_IMAGE_SIZE) {
		throw invalid(
			`Pacote ${type} inválido: tamanho do manifesto (${size} B) difere da imagem (${image.length} B) ou excede o limite de ${MAX_IMAGE_SIZE} B.`,
		);
	}
	if (signatureLength < 8 || signatureLength > 72) {
		throw invalid(
			`Pacote ${type} inválido: tamanho DER da assinatura (${signatureLength}) fora do intervalo 8–72 B.`,
		);
	}
	const signatureOffset = isV2 ? 53 : 45;
	const paddingStart = signatureOffset + signatureLength;
	if (manifest.subarray(paddingStart).some((b: number) => b !== 0xff)) {
		throw invalid(`Pacote ${type} inválido: padding do manifesto deve ser 0xFF.`);
	}
	const trailer = Buffer.alloc(isV2 ? 16 : 8);
	trailer.writeUInt32LE(counter, 0);
	trailer.writeUInt32LE(size, 4);
	if (isV2) {
		trailer.writeUInt32LE(version!, 8);
		trailer.writeUInt32LE(flags, 12);
	}
	const expected = createHash('sha256').update(image).update(trailer).digest();
	if (!manifest.subarray(8, 40).equals(expected)) {
		throw invalid(
			`Pacote ${type} inválido: digest SHA-256 do manifesto difere da imagem/counter/tamanho${isV2 ? '/versão/flags' : ''} — o artefato foi corrompido ou montado à mão.`,
		);
	}
	return image.length;
}

/**
 * Validate a tool-generated canonical .tar end-to-end:
 *  - exactly 2 members, in order: artifact.info, then the type's data member
 *  - artifact.info content == `type "<artifactType>"\n` (ASCII)
 *  - firmware-ninbus: data/firmware.npm = signed NPM manifest + image
 *  - other types: non-empty raw payload
 */
export async function validateCanonicalTar(
	tarBuffer: Buffer,
	artifactType: CanonicalArtifactType,
): Promise<CanonicalTarInfo> {
	const expectedMember = CANONICAL_DATA_MEMBERS[artifactType];
	const entries = await extractTar(tarBuffer);

	if (entries.length !== 2) {
		throw invalid(
			`Pacote inválido: TAR canônico tem exatamente 2 membros — recebido tem ${entries.length} (${entries.map((e) => e.name).join(', ') || 'vazio'}).`,
		);
	}
	// Length checked above — narrow for noUncheckedIndexedAccess.
	const info = entries[0]!;
	const data = entries[1]!;
	if (info.name !== 'artifact.info') {
		throw invalid(
			`Pacote inválido: primeiro membro deve ser artifact.info — recebido "${info.name}". (O formato antigo header-info/featureidentity.json não é mais aceito pelo firmware v4.)`,
		);
	}
	if (data.name !== expectedMember) {
		throw invalid(
			`Pacote inválido para ${artifactType}: membro de dados deve ser ${expectedMember} — recebido "${data.name}".`,
		);
	}
	const expectedInfo = Buffer.from(`type "${artifactType}"\n`, 'ascii');
	if (!info.data.equals(expectedInfo)) {
		throw invalid(
			`Pacote inválido: artifact.info deve conter 'type "${artifactType}"' — recebido ${JSON.stringify(info.data.toString('ascii'))}.`,
		);
	}
	if (data.data.length === 0) {
		throw invalid(`Pacote inválido: ${expectedMember} está vazio.`);
	}

	if (artifactType === 'firmware-ninbus') {
		const imageSize = validateNinbusManifest(data.data, artifactType);
		const magic = data.data.subarray(0, 4);
		const isV2 = magic[3] === 0x02;
		const versionPacked = isV2 ? data.data.readUInt32LE(44) : null;
		return {
			payloadSize: data.data.length,
			imageSize,
			counter: data.data.readUInt32LE(40),
			manifestFormat: isV2 ? 2 : 1,
			versionPacked,
			versionText: versionPacked !== null ? unpackVersionText(versionPacked) : null,
			allowDowngrade: isV2 ? (data.data.readUInt32LE(48) & 0x1) === 0x1 : null,
		};
	}
	return {
		payloadSize: data.data.length,
		imageSize: data.data.length,
		counter: null,
		manifestFormat: null,
		versionPacked: null,
		versionText: null,
		allowDowngrade: null,
	};
}

/** Extract all members from a tar buffer (name + content). */
function extractTar(buffer: Buffer): Promise<Array<{ name: string; data: Buffer }>> {
	return new Promise((resolve, reject) => {
		const entries: Array<{ name: string; data: Buffer }> = [];
		const extract = tar.extract();
		extract.on('entry', (header: TarHeaders, stream: NodeJS.ReadableStream, next: () => void) => {
			const chunks: Buffer[] = [];
			stream.on('data', (chunk: Buffer) => chunks.push(chunk));
			stream.on('end', () => {
				entries.push({ name: header.name, data: Buffer.concat(chunks) });
				next();
			});
			stream.on('error', reject);
		});
		extract.on('finish', () => resolve(entries));
		extract.on('error', (err: Error) =>
			reject(invalid(`TAR ilegível (não é um TAR válido): ${err.message}`)),
		);
		extract.end(buffer);
	});
}
